<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_Add_Livros extends CI_Migration {

  public function up()
  {
    $data = array(
      array(
        'titulo' => 'Os Sete Reinos',
        'descricao' => 'Cale era apenas um garoto órfão. Como todo adolescente, ele vivia as provocações feitas pelos garotos maiores e mais fortes. Tudo o que ele queria era saber quem ele era de verdade e escapar daquele tormento. Quando, após uma provocação, ele demonstra ter poderes, seu professor e mentor no orfanato o leva para uma viagem, onde descobre ser alguém muito importante e com uma missão. Os sete reinos estavam em perigo e somente ele poderia salvá-los. Contando com a ajuda de amigos pelo caminho, Cale parte na busca pela arma sagrada que poderia colocar fim a uma grande guerra e garantir a salvação de todos.',
        'autor' => 'Julie Lopo',
        'n_paginas' => 217,
        'capa' => 'http://books.google.com/books/content?id=lIcmEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'quero ler',
        'data_cadastro' => '2023-12-04',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'O Senhor dos Anéis: O retorno do rei',
        'descricao' => 'O Retorno do Rei A guerra entre os Povos Livres da Terra-média e Sauron, o Senhor Sombrio da terra de Mordor, chega a seu clímax neste terceiro volume do romance O Senhor dos Anéis. As batalhas grandiosas que estão prestes a acontecer, no entanto, são apenas o pano de fundo para o verdadeiro drama: a missão quase suicida dos hobbits Frodo e Sam, que tentam destruir o Um Anel, fonte do poder de Sauron, infiltrando-se no coração do território do Inimigo. Em O Retorno do Rei, acompanhamos o mago Gandalf e o hobbit Pippin em sua visita à a majestosa cidade de Minas Tirith, que já foi o principal baluarte dos Homens contra a ameaça de Sauron, mas que está prestes a sucumbir diante da força avassaladora do Senhor Sombrio. Outros membros da Sociedade do Anel se juntam a Aragorn, herdeiro da longa linhagem dos reis de Minas Tirith, na tentativa de evitar que a antiga capital do reino de Gondor seja destruída. Nas fronteiras de Mordor, Sam resgata Frodo, e os dois hobbits partem para o último e',
        'autor' => 'J.R.R. Tolkien',
        'n_paginas' => 548,
        'capa' => 'http://books.google.com/books/content?id=SbKuDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'quero ler',
        'data_cadastro' => '2023-12-04',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => '1984',
        'descricao' => 'Com o seu 1984, George Orwell reinventou o romance de ficção científica. Quando menino, ele adorava os romances de H. G. Wells. Como Wells, ele se apoderou das tendências de seu próprio tempo, e tentou imaginar como elas poderiam se desenvolver no longo prazo. Seu romance está situado na Pista Um, um lugar outrora conhecido como Grã-Bretanha, mas então uma província do superestado da Oceania preso em um conflito ideológico perpétuo com dois outros blocos: Eurásia e Lestásia. Como todos os grandes romances distópicos, o livro de Orwell era uma tentativa de alertar a sua própria sociedade para suas próprias tendências alarmantes. Por exemplo, ele podia ver que o que pode aterrorizar um país não é tanto a tortura pura e simples, ou restrições encobertas à liberdade de expressão, mas um adormecer dos cidadãos, através de entretenimento sofisticado e informações vazias de significado  tudo embrulhado em uma referência constante à liberdade. Assim, em 1984, a sociedade está repleta de n',
        'autor' => 'George Orwell',
        'n_paginas' => 328,
        'capa' => 'http://books.google.com/books/content?id=L-ErEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 
        'categoria' => 'quero ler',
        'data_cadastro' => '2023-06-08',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'A Culpa é das Estrelas',
        'descricao' => 'Apesar do milagre da medicina que fez diminuir o tumor que a atacara há alguns anos, Hazel nunca tinha conhecido outra situação que não a de doente terminal, sendo o capítulo final da sua vida parte integrante do seu diagnóstico. Mas com a chegada repentina ao Grupo de Apoio dos Miúdos com Cancro de uma atraente reviravolta de seu nome Augustus Waters, a história de Hazel vê-se agora prestes a ser completamente rescrita.Perspicaz, arrojado, irreverente e cru, A Culpa é das Estrelas é a obra mais ambiciosa e comovente que o premiado autor John Green nos apresentou até hoje, explorando de maneira brilhante a aventura divertida, empolgante e trágica que é estar-se vivo e apaixonado.John Green é autor de vários bestsellers do The New York Times. Recebeu o Michael L. Printz Award e o Edgar Award. Foi por duas vezes finalista do L. A. Times Book Prize. Os seus livros foram traduzidos em mais de vinte línguas. John é também o co-criador, com o seu irmão Hank, do vlogbrothers, uma série de víd',
        'autor' => 'John Green',
        'n_paginas' => 255,
        'capa' => 'http://books.google.com/books/content?id=0Ce7HDOnNFMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'lendo',
        'data_cadastro' => '2023-01-10',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'A Revolução dos Bichos',
        'descricao' => 'Cansado da exploração e dos maus tratos recebidos na Fazenda Solar, o porco Major faz um discurso inflamado poucos dias antes da sua morte e incita os animas a tomarem o poder e controle da fazenda, que até então estava na mão dos humanos. Passados três meses da morte de Major, o discurso ainda reverbera nas mentes dos animais, especialmente na dos porcos – tidos como os mais inteligentes –, e, então, uma oportunidade surge para expulsar o sr. Jones, dono da fazenda, e seus criados, momento este em que a rebelião dos bichos consegue assumir o controle total da fazenda. Liderados pelos porcos Bola de Neve e Napoleão, eles criam um novo modelo de sociedade em que os animais trabalharam para eles mesmos, e que pode ser resumido nos dois primeiros mandamentos criados: “Aquele que anda sobre duas pernas é inimigo” e “Aquele que anda sobre quatro pernas, ou possui asas, é amigo”. Autodenominados Camaradas, os animais estabelecem um sistema democrático, mas que, pouco a pouco, vai se tornando',
        'autor' => 'George Orwell',
        'n_paginas' => 141,
        'capa' => 'http://books.google.com/books/content?id=A7YzEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 
        'categoria' => 'lendo',
        'data_cadastro' => '2023-08-17',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'Dom Quixote',
        'descricao' => 'Dom Quixote, escrito pelo espanhol Miguel de Cervantes, é um clássico da literatura mundial e uma das obras mais influentes da história. Publicado pela primeira vez em 1605, o romance é uma obra-prima da ficção que tece uma narrativa na qual humor, drama e filosofia são mesclados a personagens complexos e emocionantes. A história gira em torno de Alonso Quijano, um fidalgo empobrecido que decide se tornar um cavaleiro errante e defender os oprimidos. Vestido com uma armadura antiga, dá a si mesmo o nome de Dom Quixote e parte em busca de aventuras acompanhado por seu leal escudeiro, Sancho Pança. Enquanto narra a luta de Dom Quixote para reconciliar seus sonhos idealistas com a realidade do mundo em que vive, Cervantes traz à tona questões profundas de identidade, loucura, amor e amizade, convidando o leitor a profundas reflexões acerca do mundo e de si mesmo, além de incentivar a busca pelos sonhos e ideais, ainda que pareçam loucos aos olhos alheios..',
        'autor' => 'Miguel de Cervantes',
        'n_paginas' => 863,
        'capa' => 'http://books.google.com/books/content?id=XyPbEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 
        'categoria' => 'ja li',
        'data_cadastro' => '2023-01-16',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'Cem Anos de Solidão',
        'descricao' => 'O livro mais importante de Gabriel Garcia Márquez. Neste que é um dos maiores clássicos da literatura, o prestigiado autor narra a incrível e triste história dos Buendía – a estirpe de solitários para a qual não será dada "uma segunda oportunidade sobre a terra" e apresenta o maravilhoso universo da fictícia Macondo, onde se passa o romance. É lá que acompanhamos diversas gerações dessa família, assim como a ascensão e a queda do vilarejo. Para além dos artifícios técnicos e das influências literárias que transbordam do livro, ainda vemos em suas páginas o que por muitos é considerado uma autêntica enciclopédia do imaginário, num estilo que consagrou o colombiano como um dos maiores autores do século XX..',
        'autor' => 'Gabriel García Márquez',
        'n_paginas' => 417,
        'capa' => 'http://books.google.com/books/content?id=MAqQDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'ja li',
        'data_cadastro' => '2023-05-30',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'O Pequeno Príncipe',
        'descricao' => 'Palavras de amor e sabedoria que cativam o coração e a alma fazem parte deste clássico que já conquistou milhões de leitores em todo o mundo. Durante a sua jornada por planetas diferentes e também pelo planeta Terra, o Pequeno Príncipe nos ensina lições valiosas sobre as escolhas, relações humanas e sentimentos como a solidão, a saudade, a amizade e a distância. Já há mais de sete décadas encantando as gerações de leitores, O Pequeno Príncipe é publicado agora pela Mafra Editorial, nesta edição especial, que conta com as ilustrações originais do autor e também com ilustrações inéditas. Esta é considerada uma das maiores obras literárias do século XX, sendo um dos livros mais traduzidos do mundo, para cerca de 253 idiomas. Foi publicada pela primeira vez no ano de 1942 nos Estados Unidos e, três anos depois, na França. Biografia do autor Antoine de Saint-Exupéry Antoine de Saint-Exupéry nasceu em uma família aristocrática, na data de 29 de junho de 1900, na cidade de Lyon, França. Escre',
        'autor' => 'Antoine de Saint-Exupéry',
        'n_paginas' => 96,
        'capa' => 'http://books.google.com/books/content?id=1D9KEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'ja li',
        'data_cadastro' => '2023-04-06',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'Crime e Castigo',
        'descricao' => 'Nova tradução direto do russo, a cargo de Rubens Figueiredo, de um dos romances mais importantes e influentes de todos os tempos. Crime e castigo é a obra mais célebre de Dostoiévski e um dos romances fundamentais da literatura ocidental. Escrita entre 1865 e 1866, quando Dostoiévski tinha 45 anos, foi publicada em partes na revista Rússki Viéstnik [O Mensageiro Russo], a mesma que vinha publicando, na época, o romance Guerra e paz, de Liev Tolstói. A ideia do livro surgiu quando Dostoiévski propôs a Katkóv, editor da revista, redigir um "relato psicológico de um crime". Na obra, Raskólnikov, um rapaz sombrio e orgulhoso, retraído mas também aberto à observação humana, precisa interromper seus estudos por falta de dinheiro. Devendo o aluguel à proprietária do cubículo desconfortável em que vive, ele se sente esmagado pela pobreza. Ao mesmo tempo, acha que está destinado a um grande futuro e, desdenhoso da moralidade comum, julga ter plenos direitos para cometer um crime – o que fará de',
        'autor' => 'Fiódor Dostoiévski',
        'n_paginas' => 551,
        'capa' => 'http://books.google.com/books/content?id=nO2MDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'ja li',
        'data_cadastro' => '2023-01-25',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'Orgulho e Preconceito',
        'descricao' => '"É verdade universalmente reconhecida que um homem solteiro em posse de boa fortuna deve estar necessitado de esposa." É com essas palavras que Jane Austen inicia "Orgulho e preconceito", conduzindo o leitor diretamente ao lar dos Bennet, família com não menos que cinco noivas em potencial: Jane, Elizabeth, Mary, Kitty e Lydia. Quando o sr. Bingley e o sr. Darcy, dois jovens distintos, chegam a Hertfordshire, todas ficam em alerta: eles são solteiros, bonitos e, claro, donos de uma boa fortuna. O que poderia ser uma típica história de amor é, nas mãos de uma das escritoras de língua inglesa mais difundidas pelo mundo, um espetáculo de grandes personagens e diálogos sagazes, com um timing perfeito para a ironia.',
        'autor' => 'Jane Austen',
        'n_paginas' => 279,
        'capa' => 'http://books.google.com/books/content?id=UGIC7N0Op2MC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'ja li',
        'data_cadastro' => '2023-01-28',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'A Metamorfose',
        'descricao' => 'Embora tenhamos escrito incontáveis obras desde o advento da escrita, há alguma arte que parece vencer o próprio fluxo do tempo, algumas histórias que se tornaram já mitologia por onde passaram, e que já foram lidas e encenadas pelas mentes de milhões e milhões de seres humanos. A Coleção clássicos eternos reconhece a importância de trazer esta luz para ser refletida no maior número de espelhos possível, e cada um de nós é um espelho, e a luz foi criada para ser refletida. Assim sendo, temos o compromisso de trazer edições cuidadosamente elaboradas dos grandes gênios de outrora, por um preço acessível  principalmente por se tratar de material em domínio público. [Metamorfose, de Kafka] Um clássico da literatura mundial ou uma espécie de “pegadinha literária”, com o perdão do termo? De fato, Kafka foi genial por conseguir evitar, a todo momento, que o seu leitor conseguisse responder definitivamente a tal pergunta. É perfeitamente compreensível que muita g',
        'autor' => 'Franz Kafka',
        'n_paginas' => 55,
        'capa' => 'http://books.google.com/books/content?id=TCHXDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'ja li',
        'data_cadastro' => '2023-10-15',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'A Revolta de Atlas',
        'descricao' => 'Considerado o livro mais influente nos Estados Unidos depois da Bíblia, segundo a Biblioteca do Congresso americano, A revolta de Atlas é um romance monumental. Com mais de 11 milhões de livros vendidos, a mensagem transformadora de Ayn Rand conquistou uma legião de leitores e fãs: cada indivíduo é responsável por suas ações e por buscar a liberdade e a felicidade como valores supremos. A história se passa numa época imprecisa, quando as forças políticas de esquerda estão no poder. Último baluarte do que ainda resta do capitalismo num mundo infestado de repúblicas populares, os Estados Unidos estão em decadência e sua economia caminha para o colapso. Nesse cenário desolador em que a intervenção estatal se sobrepõe a qualquer iniciativa privada de reerguer a economia, os principais líderes da indústria, do empresariado, das ciências e das artes começam a sumir sem deixar pistas. Com medidas arbitrárias e leis manipuladas, o Estado logo se apossa de suas propriedades e invenções, mas não',
        'autor' => 'Ayn Rand',
        'n_paginas' => 1088,
        'capa' => 'http://books.google.com/books/content?id=GT5UEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'quero ler',
        'data_cadastro' => '2023-10-10',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'O Nome do Vento',
        'descricao' => '"Devorei em um dia e já estou louco pelo próximo. Ele é muito bom, esse tal de Rothfuss." – George R. R. Martin, autor de A guerra dos tronos Ninguém sabe ao certo quem é o herói ou o vilão desse fascinante universo criado por Patrick Rothfuss. Na realidade, essas duas figuras se concentram em Kote, um homem enigmático que se esconde sob a identidade de proprietário da hospedaria Marco do Percurso. Da infância numa trupe de artistas itinerantes, passando pelos anos vividos numa cidade hostil e pelo esforço para ingressar na escola de magia, O nome do vento acompanha a trajetória de Kote e as duas forças que movem sua vida: o desejo de aprender o mistério por trás da arte de nomear as coisas e a necessidade de reunir informações sobre o Chandriano – os lendários demônios que assassinaram sua família no passado. Quando esses seres do mal reaparecem na cidade, um cronista suspeita de que o misterioso Kote seja o personagem principal de diversas histórias que rondam a região e decide aprox',
        'autor' => 'Patrick Rothfuss',
        'n_paginas' => 662,
        'capa' => 'http://books.google.com/books/content?id=7-9zwIWkAlEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'quero ler',
        'data_cadastro' => '2023-03-27',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'A Guerra dos Tronos',
        'descricao' => 'A guerra dos tronos é o primeiro livro da série best-seller internacional As Crônicas de Gelo e Fogo, que deu origem à adaptação de sucesso da HBO, Game of Thrones . O verão pode durar décadas. O inverno, toda uma vida. E a guerra dos tronos começou. Como Guardião do Norte, lorde Eddard Stark não fica feliz quando o rei Robert o proclama a nova Mão do Rei. Sua honra o obriga a aceitar o cargo e deixar seu posto em Winterfell para rumar para a corte, onde os homens fazem o que lhes convém, não o que devem... e onde um inimigo morto é algo a ser admirado. Longe de casa e com a família dividida, Eddard se vê cada vez mais enredado nas intrigas mortais de Porto Real, sem saber que perigos ainda maiores espreitam a distância. Nas florestas ao norte de Winterfell, forças sobrenaturais se espalham por trás da Muralha que protege a região. E, nas Cidades Livres, o jovem Rei Dragão exilado na Rebelião de Robert planeja sua vingança e deseja recuperar sua herança de família: o Trono de Ferro de ',
        'autor' => 'George R.R. Martin',
        'n_paginas' => 592,
        'capa' => 'http://books.google.com/books/content?id=DLKMDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'ja li',
        'data_cadastro' => '2023-08-06', 
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'Duna',
        'descricao' => 'O Imperium vive um interregno após Paul Atreides abdicar de seu título de imperador e entregar-se ao deserto. Sua irmã, Alia, ascende ao poder como regente enquanto os filhos de Muad&#039;Dib não são capazes de assumir o Trono do Leão. Herdeiros não só do poder político e econômico de seu pai, os gêmeos também carregam em suas veias toda a carga genética manipulada por séculos pela Irmandade Bene Gesserit. Mas a hegemonia dos Atreides está ameaçada. De seu exílio em Salusa Secundus, os membros da despojada Casa Corrino tramam uma complexa teia para retomar as rédeas do Imperium e se vingar de todos os envolvidos em sua queda. Filhos de Duna fecha com brilhantismo o arco de história iniciado com Paul Atreides no épico Duna e em sua sequência, Messias de Duna, retomando os temas políticos e existenciais com a mesma maestria dos livros que o precederam.',
        'autor' => 'Frank Herbert',
        'n_paginas' => 592,
        'capa' => 'http://books.google.com/books/content?id=h82uCgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'quero ler',
        'data_cadastro' => '2023-08-01', 
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'O Silmarillion',
        'descricao' => '"O Silmarillion" é um relato dos Dias Antigos da Primeira Era do mundo criado por J.R.R. Tolkien. É a história longínqua para a qual os personagens de "O Senhor dos Anéis" e "O Hobbit" olham para trás, e em cujos eventos alguns deles, como Elrond e Galadriel, tomaram parte. Os contos de "O Silmarillion" se passam em uma época em que Morgoth, o Primeiro Senhor Sombrio, habitava a Terra-média, e os Altos-Elfos guerreavam contra ele pela recuperação das Silmarils, as joias que continham a pura luz de Valinor. O livro começa com "O Ainulindalë", o mito da criação do Universo, seguido pelo "Valaquenta", onde estão descritas a natureza e os poderes de cada um dos deuses. O "Akallâbeth" narra o apogeu e a queda do reino da grande ilha de Númenor no final da Segunda Era e "Dos Anéis de Poder" fala dos grandes eventos no final da Terceira Era, como narrado em "O Senhor dos Anéis".',
        'autor' => 'J.R.R. Tolkien',
        'n_paginas' => 365,
        'capa' => 'http://books.google.com/books/content?id=B3uFDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'quero ler',
        'data_cadastro' => '2023-09-15',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'O Alquimista',
        'descricao' => 'O alquimista - um clássico contemporâneo sobre o poder transformador dos sonhos. Combinando espiritualidade, sabedoria e misticismo, O alquimista é uma inspiradora e emocionante história de autodescoberta que vem transformando a vida de milhões de leitores ao redor do mundo há mais de trinta anos. Santiago, um jovem pastor da Andaluzia, parte rumo ao Egito em busca de um tesouro escondido entre as Pirâmides. O que ele não sabe é que sua jornada o levará a riquezas muito diferentes – e mais satisfatórias – do que ele estava esperando. Ao longo do caminho, uma cigana, um homem que se diz rei e um alquimista lhe indicam a direção em que deve seguir e o ajudam a perceber que o maior tesouro se encontra dentro dele mesmo. Com a prosa poética de Paulo Coelho, este romance encantador nos recorda da sabedoria de ouvir nossos corações, reconhecer as oportunidades da vida e, mais importante, sempre seguir nossos sonhos. &quot;O alquimista é esperançoso e inspirador. Sua história ensina que devem',
        'autor' => 'Paulo Coelho',
        'n_paginas' => 163,
        'capa' => 'http://books.google.com/books/content?id=pfctDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'ja li',
        'data_cadastro' => '2023-01-01',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'O Senhor das Moscas',
        'descricao' => 'Um romance indispensável de William Golding, vencedor do prêmio Nobel, sobre a natureza do mal e a tênue linha que separa a civilidade da barbárie. Considerado um dos 100 melhores romances do século XX pela Modern Library. Senhor das Moscas é um dos romances essenciais da literatura mundial. Adaptado duas vezes para o cinema e traduzido para 35 idiomas, o clássico de William Golding já foi visto como uma alegoria, uma parábola, um tratado político e até mesmo uma visão do apocalipse. Durante a Segunda Guerra Mundial, um avião cai numa ilha deserta e os únicos sobreviventes são um grupo de meninos. Liderados por Ralph, eles procuram se organizar enquanto esperam um possível resgate. Mas aos poucos esses garotos aparentemente inocentes transformam a ilha numa visceral disputa pelo poder, e sua selvageria rasga a fina superfície da civilidade. Ao narrar essa história sobre meninos perdidos numa ilha, aos poucos se deixando levar pela barbárie, Golding constrói uma reflexão sobre o limite ',
        'autor' => 'William Golding',
        'n_paginas' => 208,
        'capa' => 'http://books.google.com/books/content?id=cs8tEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'quero ler',
        'data_cadastro' => '2023-09-17',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'A Sangue Frio',
        'descricao' => 'O americano Truman Capote foi um escritor versátil: produziu textos de qualidade em vários gêneros (contos, peças, reportagens, adaptações para TV e roteiros para filmes). Mas sua grande obra foi o romance-reportagem A sangue frio, que conta a história da morte de toda a família Clutter, em Holcomb, Kansas, e dos autores da chacina. Capote decidiu escrever sobre o assunto ao ler no jornal a notícia do assassinato da família, em 1959. Quase seis anos depois, em 1965, a história foi publicada em quatro partes na revista The New Yorker. Além de narrar o extermínio do fazendeiro Herbert Clutter, de sua esposa Bonnie e dos filhos Nancy e Kenyon - uma típica família americana dos anos 50, pacata e integrada à comunidade -, o livro reconstitui a trajetória dos assassinos. Perry Smith e Dick Hikcock planejaram o crime acreditando que se apropriariam de uma fortuna, mas não encontraram praticamente nada. Perry era um sonhador. Teve criação conturbada e violenta, e achava que a vida lhe tinha da',
        'autor' => 'Truman Capote',
        'n_paginas' => 343,
        'capa' => 'http://books.google.com/books/content?id=MxhFiSjwlb8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'quero ler',
        'data_cadastro' => '2023-01-17',
        'usuario_id' => 1,
      ),
      array(
        'titulo' => 'O Hobbit',
        'descricao' => 'Edição com mapas, capa dura, fitilho, as ilustrações originais de J.R.R. Tolkien e um pôster de Valfenda exclusivo! Bilbo Bolseiro era um dos mais respeitáveis hobbits de todo o Condado até que, um dia, o mago Gandalf bate à sua porta. A partir de então, toda sua vida pacata e campestre soprando anéis de fumaça com seu belo cachimbo começa a mudar. Ele é convocado a participar de uma aventura por ninguém menos do que Thorin Escudo-de-Carvalho, um príncipe do poderoso povo dos Anãos. Esta jornada fará Bilbo, Gandalf e 13 anãos atravessarem a Terra-média, passando por inúmeros perigos, como os imensos trols, as Montanhas Nevoentas infestadas de gobelins ou a muito antiga e misteriosa Trevamata, até chegarem (se conseguirem) na Montanha Solitária. Lá está um incalculável tesouro, mas há um porém. Deitado em cima dele está Smaug, o Dourado, um dragão malicioso que... bem, você terá que ler para descobrir. Lançado em 1937, O Hobbit é um divisor de águas na literatura de fantasia mundial. Ma',
        'autor' => 'J.R.R. Tolkien',
        'n_paginas' => 310,
        'capa' => 'http://books.google.com/books/content?id=2LeZDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        'categoria' => 'quero ler',
        'data_cadastro' => '2023-09-21',
        'usuario_id' => 1,
      ),
    );
    $this->db->insert_batch('livros', $data);
  }

  public function down()
  {
    $this->db->query('TRUNCATE TABLE livros WHERE usuario_id=1');
  }
}
